version: "3"

services:

  m2m_chat_service:
    container_name: "m2m_chat_service"
    image: mfatin/messenger:1.0
    volumes:
      - ./microservices/m2m_chat_service:/usr/src/messenger/microservices/m2m_chat_service
      - ./microservices/_third_party:/usr/src/messenger/microservices/_third_party
    command: bash -c "cd /usr/src/messenger/microservices/m2m_chat_service && chmod +x ./build.sh && ./build.sh"

  mongodb:
    container_name: "mongodb"
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongodb:/usr/src/messenger/mongodb

  keycloak:
    container_name: "keycloak"
    image: jboss/keycloak

  nginx_server:
    container_name: "nginx_server"
    image: nginx
    ports:
      - 8080:80 # localhost:8080
