version: "3.7"

services:
  m2m_chat_service:
    container_name: m2m_chat_service
    hostname: m2m_chat_service
    image: mfatin/messenger:latest
    env_file:
      - ./microservices/m2m_chat_service/server.env # use env variable in container
    # image capture executable file
    command: bash -c "cd /usr/src/messenger/microservices/m2m_chat_service/_build && chmod +x ./m2m_chat_service && ./m2m_chat_service"
    ports:
      - "9000:${M2M_CHAT_SERVICE_PORT}" # localhost:9000

  mongodb:
    container_name: "mongodb"
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongodb:/usr/src/messenger/mongodb

  keycloak:
    container_name: "keycloak"
    image: jboss/keycloak

  nginx_server:
    container_name: "nginx_server"
    image: nginx
    ports:
      - 8080:80 # localhost:8080
