version: "3"

services:

  m2m_chat_service:
    container_name: "m2m_chat_service"
    build:
      context: ./microservices
      dockerfile: ./Dockerfile.m2m_chat_service
    command: bash -c "cd m2m_chat_service && chmod +x ./build.sh && ./build.sh"

  mongodb:
    container_name: "mongodb"
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password

  nginx_server:
    container_name: "nginx_server"
    image: nginx
    ports:
      - 8080:80 # localhost:8080
