version: "3"

services:
  mongodb:
    container_name: "mongodb"
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongodb:/usr/src/messenger/mongodb

  keycloak:
    container_name: "keycloak"
    image: jboss/keycloak

  nginx_server:
    container_name: "nginx_server"
    image: nginx
    ports:
      - 8080:80 # localhost:8080
