version: "3.7"

services:
  m2m_chat_service:
    container_name: m2m_chat_service
    hostname: m2m_chat_service
    image: mfatin/messenger:latest
    env_file:
      - server.env # use env variable inside container
    volumes:
      - .:/usr/src/messenger/microservices/m2m_chat_service
      - ./../core:/usr/src/messenger/microservices/core
    command: bash -c "cd /usr/src/messenger/microservices/m2m_chat_service/_build && chmod +x ./m2m_chat_service && ./m2m_chat_service"
    ports:
      - "9000:${SERVER__PORT}" # localhost:9000
    networks:
      net:
        ipv4_address: ${SERVER__ADDRESS}

networks:
  net: # network name
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
