name: pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build docker compose
        run: docker-compose -f docker-compose.yml build
      - name: Install Python depts
        run: sudo apt-get install -y --no-install-recommends tox python3
      - name: Install C++ depts
        run: sudo apt-get install -y --no-install-recommends libboost-all-dev libgtest-dev clang-14
      - name: Python tests
        run: chmod +x ./messenger_qa/create_venv.sh ./messenger_qa/run_tests.sh && ./messenger_qa/create_venv.sh && ./messenger_qa/run_tests.sh
      - name: Build (m2m_chat_service)
        run: chmod +x ./microservices/m2m_chat_service/build.sh && ./microservices/m2m_chat_service/build.sh
      - name: Unit tests (m2m_chat_service)
        run: chmod +x ./microservices/m2m_chat_service/_build/m2m_chat_service_unit_test && ./microservices/m2m_chat_service/_build/m2m_chat_service_unit_test
      - name: Unit tests (core library)
        run: chmod +x ./microservices/core/tests/gtest/build.sh ./microservices/core/tests/gtest/run_tests.sh && ./microservices/core/tests/gtest/build.sh && ./microservices/core/tests/gtest/run_tests.sh
      - name: Fuzz tests (core library)
        run: chmod +x ./microservices/core/tests/fuzz/build.sh ./microservices/core/tests/fuzz/run_tests_pipeline.sh && ./microservices/core/tests/fuzz/build.sh && ./microservices/core/tests/fuzz/run_tests_pipeline.sh
