name: pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install depts
        run: sudo apt-get install -y cppcheck
      - name: Build
        run: docker-compose -f docker-compose.yml build
      - name: Cppcheck (m2m_chat_service)
        run: chmod +x microservices/m2m_chat_service/run_cppcheck.sh && ./microservices/m2m_chat_service/run_cppcheck.sh
      - name: Tests (m2m_chat_service)
        run: docker-compose -f docker-compose.yml build && cd microservices/m2m_chat_service && chmod +x ./build.sh && ./build.sh && cd _build && chmod +x m2m_chat_service_unit_test && ./m2m_chat_service_unit_test
