name: pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build docker compose
        run: docker-compose -f docker-compose.yml build
      - name: Install depts
        run: sudo apt-get install -y tox python3
      - name: Python tests
        run: chmod +x ./messenger_qa/create_venv.sh ./messenger_qa/run_tests.sh && ./messenger_qa/create_venv.sh && ./messenger_qa/run_tests.sh
      - name: Build (m2m_chat_service)
        run: chmod +x ./microservices/m2m_chat_service/build.sh && ./microservices/m2m_chat_service/build.sh
      - name: Unit tests (m2m_chat_service)
        run: chmod +x ./microservices/m2m_chat_service/_build/m2m_chat_service_unit_test && ./microservices/m2m_chat_service/_build/m2m_chat_service_unit_test
